ktor {
    deployment {
        port = 8083
        host = "0.0.0.0"
    }
    application {
        modules = [ com.maisforte.training.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/maisforte"
    driver = "org.postgresql.Driver"
    user = "postgres"
    password = "postgres"
}
